version: "3"

services:
    db:
        image: postgres:9.6.2
        env_file:
            - .docker/env/postgres.${APP_ENV}.env
        ports:
            - "5432:5432"
        networks:
            - network1

    django:
        build:
            context: .
            dockerfile: ./.docker/django.dockerfile
        ports:
            - "8000:8000"
        env_file:
            .docker/env/django.${APP_ENV}.env
        volumes:
            - .:/var/www/
        working_dir: /var/www
        depends_on:
          - "db"
        command:
            bash -c ".docker/scripts/wait-for-postgres.sh &&
                     python manage.py makemigrations &&
                     python manage.py migrate &&
                     python manage.py runserver 0.0.0.0:8000"
        networks:
            - network1

    rabbitmq:
        build:
            context: .
            dockerfile: ./.docker/mq.dockerfile
        ports:
            - "5672:5672"
            - "15672:15672"
        env_file:
            .docker/env/rabbitmq.${APP_ENV}.env
        networks:
            - network1

    worker:
        build:
            context: .
            dockerfile: ./.docker/django.dockerfile
        command: celery -A eoj worker -l info
        env_file:
            .docker/env/django.${APP_ENV}.env
        depends_on:
            - rabbitmq
        networks:
            - network1


networks:
    network1:
        driver: bridge
