version: "3"

services:
    db:
        image: postgres:9.6.2
        hostname: db
        env_file:
            - .docker/env/postgres.${APP_ENV}.env
        ports:
            - "5432:5432"
        networks:
            - network1

    django:
        container_name: django1
        build:
            context: .
            dockerfile: ./.docker/django.dockerfile
        ports:
            - "8000:8000"
        env_file:
            .docker/env/django.${APP_ENV}.env
        volumes:
            - .:/var/www/
        working_dir: /var/www
        depends_on:
          - "db"
        command:
            bash -c ".docker/scripts/wait-for-postgres.sh &&
                     python manage.py makemigrations &&
                     python manage.py migrate &&
                     python manage.py runserver 0.0.0.0:8000"
        networks:
            - network1

    # rabbit:
    #     hostname: rabbit
    #     image: rabbitmq:3.6
    #     ports:
    #         - "5672:5672"
    #         - "15672:15672"

networks:
    network1:
        driver: bridge
