version: "3"

services:
    django:
        container_name: django1
        build:
            context: .
            dockerfile: ./.docker/django.dockerfile
        ports:
            - "8000:8000"
        env_file:
            .docker/env/django.${APP_ENV}.env
        volumes:
            - .:/var/www/${APP_NAME}
        working_dir: /var/www/${APP_NAME}
        networks:
            - network1

networks:
    network1:
        driver: bridge
