# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 17:36
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problemset', '0015_auto_20170602_2036'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to=core.models.source_directory_path)),
                ('status', models.IntegerField(choices=[(0, 'Error'), (1, 'Pending'), (2, 'Tests passed'), (3, 'Wrong answer')], default=1)),
                ('language', models.IntegerField(choices=[(0, 'C++'), (1, 'Python')])),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='error',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SubmissionError'),
        ),
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problemset.Problem'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
