# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_submission_source_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Error'), (1, 'Pending'), (2, 'Tests passed'), (3, 'Wrong answer'), (4, 'TIME_LIMIT_EXCEEDED')], default=1),
        ),
    ]
