# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20170626_2236'),
        ('core', '0003_auto_20170624_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
        ),
    ]
