# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_post_on_homepage', 'Can post on homepage'),)},
        ),
    ]
