# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('statement', models.TextField()),
                ('publish_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
