# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0002_problem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='testcase_directory_path')),
                ('output_file', models.FileField(upload_to='testcase_directory_path')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problemset.Problem')),
            ],
        ),
    ]
