# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0004_auto_20170510_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Error')], default=0),
        ),
    ]
