# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import problemset.models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0006_auto_20170511_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='input_file',
            new_name='input_data_file',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='output_file',
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_source_file',
            field=models.FileField(default='', upload_to=problemset.models.testcase_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcase',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problemset.Problem'),
        ),
    ]
