# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0007_auto_20170520_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='sample_input',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_output',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
