# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import problemset.models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0008_auto_20170520_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='solution_source_file',
            field=models.FileField(upload_to=problemset.models.solution_directory_path),
        ),
    ]
