# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0009_auto_20170522_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.IntegerField(choices=[(0, 'C++')], default=0),
            preserve_default=False,
        ),
    ]
