# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0011_auto_20170522_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Error'), (1, 'Pending'), (2, 'Tests passed'), (3, 'Wrong answer')], default=1),
        ),
    ]
