# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0014_auto_20170602_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='error',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='SubmissionError',
        ),
    ]
