# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0015_auto_20170602_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solution_language',
            field=models.IntegerField(choices=[(0, 'C++'), (1, 'Python')], default=0),
            preserve_default=False,
        ),
    ]
