# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0016_problem_solution_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='output',
            field=models.TextField(null=True),
        ),
    ]
