# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0018_auto_20170604_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='problemset.Tag'),
        ),
    ]
