# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 15:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0019_auto_20170605_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_description',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='ouptut_description',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
