# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0020_auto_20170605_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='ouptut_description',
            new_name='output_description',
        ),
    ]
