# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0021_auto_20170605_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
